language: node_js
node_js:
  - "8"

cache:
  yarn: true
  pip: true
  directories:
    - node_modules
    - generated

stages:
  - install
  - generate
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: install
      install: npm install --global yarn
      script: yarn

    - stage: generate
      script: npm run stage:generate

    - stage: build
      script: npm run stage:build

    - stage: test
      script: npm run lint:js

    - stage: test
      script: npm run lint:markdown

    - stage: test
      script: npm run lint:social

    - stage: test
      install: sudo pip install proselint
      script: npm run lint:prose

    - stage: deploy
      script: bash ./src/scripts/deploy.sh
