sudo: required
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  pip: true
  directories:
    - node_modules
    - build

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      before_install: npm install --global yarn
      install: yarn
      script: npm run build

    - stage: test
      script: npm run lint:js

    - stage: test
      script: npm run lint:markdown

    - stage: test
      script: npm run lint:social

    - stage: test
      install: sudo pip install proselint
      script: npm run lint:prose

    - stage: deploy
      script: bash ./src/scripts/deploy.sh
